### ISSUE TITLE
ORM注解

### ISSUE THREAD

**Issue by ijackwu** [imiphp/imi#49]
```
/**
 * 定义为实体
 * @Entity
 * 指定实体为test，复合主键id和a
 * @Table(name="test", id={"id", "a"})
 */
```

注解Table写死表名称，有种场景，需要动态拆分表。
比如通过hash，传入一个id，hass(id) 自动分配表，这个时候ORM注解就无法实现了

**Comment by Yurunsoft** [comment]
目前 imi 的模型还不支持分表

**Comment by Yurunsoft** [comment]
Fork 模型特性，支持在运行阶段创建一个新的模型类，这个类从原模型继承。
并且支持指定新模型类使用的：数据库名、数据表名、连接池名。
<https://doc.imiphp.com/v2.0/components/orm/RDModel.html>
