### ISSUE TITLE
orm问题

### ISSUE THREAD

**Issue by Mjc960512** [imiphp/imi#97]
#### 一.关联指定不自动查询
手动查询的关联，下列方法均无法实现
```
// 设想中实现方法一
Model::query()->where('status','=',1)->paginate(1, 15)->queryRelations('关联属性名');

// or 设想中实现方法二
Model::query()->where('status','=',1)->queryRelations('关联属性名')->paginate(1, 15)

// or 设想中实现方法三
Model::query()->where('status','=',1)->queryRelations('关联属性名')->select();

// or 设想中实现方法四
Model::queryRelations('关联属性名')->where('status','=',1)->select() or paginate();
```
不知是我操作问题还是别的。

#### 二.驼峰命名
在生成表的时候，已经指定注解@Entity(false)，按理说应该不会驼峰命名了，但在关联查询的结果中，字段还是驼峰命名

![image](https://user-images.githubusercontent.com/41005585/125063088-a37be000-e0e1-11eb-9b79-da40c2457279.png)

### 三.多层关联时
这边代码是：表1一对多多态关联表2，表2一对一关联表3，查询时表三结果为null，不知道是不是配置问题

**Comment by Mjc960512** [comment]
还是强烈建议关联的时候可以单独指定条件，给一个查询器where，page，order，limit

**Comment by Yurunsoft** [comment]
![image](https://user-images.githubusercontent.com/20104656/125149016-ed5bd900-e168-11eb-8c60-b224ba3e5012.png)

第一个问题你没按文档说的操作。文档里是`$model`对象的`queryRelations`方法，imi里所有模型的对象，都是代表一条记录，而不是查询构建器。

第二个问题，更新最新版，在`start_position`所在模型类指定注解`@Entity(false)`

第三个问题，大概率是配置错了

问题2、3可以提供代码截图，更加直观

**Comment by Mjc960512** [comment]
所以查询列表是不能用这个方法的对吗

> ![图像](https://user-images.githubusercontent.com/20104656/125149016-ed5bd900-e168-11eb-8c60-b224ba3e5012.png)
> 
> 文档里是`$model`对象的操作`queryRelations`，模仿里所有模型的对象，都是代表记录，而不是构建器。
> 
> 在第二个问题，更新最新版，`start_position`某模型类指定的注解`@Entity(false)`
> 
> 第三个争议，大辩论是配置错了
> 
> 问题2、3可以提供代码截图，更加直观

所以第一个问题只能在find方法后使用吗

**Comment by Yurunsoft** [comment]
列表查出来后可以循环调用也是可以的

**Comment by Yurunsoft** [comment]
问题一已经增加实现了一个辅助方法：<https://github.com/imiphp/imi/commit/85255f83a7b6a5dfc1c1b4e22d23bf1688794c0a>
问题二bug修复：https://github.com/imiphp/imi/commit/f6e7c6b6a189ff0699bbe4923b807f731e730e0e
